import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans } from "next/font/google";
import { cn } from "@/lib/utils";

const workSans = Work_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={cn("font-sans", workSans.variable)}>
      <body>{children}</body>
    </html>
  );
}
